name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2
      - name: Login to Docker Hubs
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Building docker image
        run: sudo docker build . -t gauri65/aplus
      - name: Push docker image to Hub
        run: sudo docker push gauri65/aplus:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pulling Image from docker Hub
        run: sudo docker pull gauri65/aplus:latest

      - name: Remove existing Containers
        run: sudo docker ps -a
      - name: Stop existing Containers
        run: sudo docker stop aplus_container || true
      - name: Remove existing containers
        run: sudo docker rm -f aplus_container || true
      - name: Run a container HI
        run: sudo docker run -d -p 8000:8000 --name aplus_container gauri65/aplus
      - name: Log the container
        run: sudo docker logs aplus_container
